REVOKE EXECUTE ON FUNCTION public.create_department_reviews() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.maybe_issue_certificate() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.notify_review_change() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.touch_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.staff_in_department(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.owns_application(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.can_see_review(uuid, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.staff_in_department(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.owns_application(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_see_review(uuid, uuid) TO authenticated;
